kind: pipeline
type: docker
name: default

steps:
  - name: git-pull-and-restart-container
    image: docker:stable
    commands:
      - cd /root/testDrone/testdrone
      - git pull  # Получение изменений из pull request
      - docker-compose down  # Остановка контейнера
      - docker-compose up -d --build  # Запуск контейнера с пересборкой