kind: pipeline
type: docker
name: default

steps:

  - name: clone-repository
    image: alpine/git
    commands:
      # - cd /root/testDrone/testdrone
      - git clone https://github.com/darkClaw921/testDrone.git
  
  - name: build-and-restart-myservice-container
    image: docker/compose:1.29.2
    commands:
      - docker-compose -f docker-compose.yml build myservice  # Сборка образа для нужного сервиса
      - docker-compose -f docker-compose.yml up -d myservice  # Запуск контейнера для нужного сервиса

  # - name: git-pull-and-restart-container
  #   image: docker:stable
  #   commands:
  #     - ls
  #     - pwd
  #     - cd testDrone/testdrone
  #     # - git pull  # Получение изменений из pull request
  #     - ls
  #     - pwd
  #     - python3 testdrone/main.py
      # - docker-compose down  # Остановка контейнера
      # - docker-compose up -d --build  # Запуск контейнера с пересборкой