kind: pipeline
type: docker
name: default

steps:

  - name: clone-repository
    image: alpine/git
    commands:
      # - cd /root/testDrone/testdrone
      - git clone https://github.com/darkClaw921/testDrone.git /root/testDrone/testdrone


  - name: git-pull-and-restart-container
    image: docker:stable
    commands:
      - ls
      - pwd
      - cd /root/testDrone/testdrone
      - git pull  # Получение изменений из pull request
      # - docker-compose down  # Остановка контейнера
      # - docker-compose up -d --build  # Запуск контейнера с пересборкой